### ISSUE TITLE
Exit_to info duplication

### ISSUE THREAD

**Issue by Caboosey** [k1wiosm/checkautopista2#16] opened 2016-07-17 05:32 UTC
After issue #15 was fixed. If an exit has more than 1 exit like a split where that motorway ends and has Exit_to=*, it will appear as many times per number motorway_links are attached.

This can be seen at the I-10 termination in Jacksonville, FL.

http://k1wiosm.github.io/checkautopista2/?id=1024908&lat=30.3220&lon=-81.7018&z=15

**Comment by k1wiosm** [comment] 2016-07-17 07:53
Since there are two `motorway_links`, checkautopista2 will show two exit signs. And since `exit_to` is used in the `motorway_junction`, it has no way of knowing to which of the two `motorway_links` the information in `exit_to` is referred to. So it shows it in both. Finally, since `destination` tags are used in one of the `motorway_links`, that info gets priority and `exit_to` is not used in that `motorway_link`.

What would be the expected behavior here?

**Comment by Caboosey** [comment] 2016-07-17 08:10
I would expect to only have the one Exit_to showing for a split exit. For a regular exit with the recent changes, i saw no issues.

I'm trying to phase out Exit_to by replacing it with destination tags since destination tags works better in details and for split exits.

**Comment by k1wiosm** [comment] 2016-07-17 08:30
I'm not sure I understand what you mean by "I would expect to only have the one Exit_to showing for a split exit".

You think there should be just one exit sign?

**Comment by k1wiosm** [comment] 2016-08-19 15:41
If you have not any more comments I will close this issue.

**Closed** 2016-08-24 13:34 UTC
